# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: occupy_dev_channel.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='occupy_dev_channel.proto',
  package='protobuf.occupy_dev_channel',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18occupy_dev_channel.proto\x12\x1bprotobuf.occupy_dev_channel\"\xab\x01\n\x07Request\x12\x0f\n\x07\x62Occupy\x18\x01 \x01(\x08\x12\x12\n\nstrDevCode\x18\x02 \x01(\t\x12H\n\nmapChannel\x18\x03 \x03(\x0b\x32\x34.protobuf.occupy_dev_channel.Request.MapChannelEntry\x1a\x31\n\x0fMapChannelEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\"B\n\x07Respond\x12\x10\n\x08\x62Success\x18\x01 \x01(\x08\x12\x12\n\nstrDevCode\x18\x02 \x01(\t\x12\x11\n\tstrErrors\x18\x03 \x01(\tb\x06proto3'
)




_REQUEST_MAPCHANNELENTRY = _descriptor.Descriptor(
  name='MapChannelEntry',
  full_name='protobuf.occupy_dev_channel.Request.MapChannelEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='protobuf.occupy_dev_channel.Request.MapChannelEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='protobuf.occupy_dev_channel.Request.MapChannelEntry.value', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=229,
)

_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='protobuf.occupy_dev_channel.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bOccupy', full_name='protobuf.occupy_dev_channel.Request.bOccupy', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strDevCode', full_name='protobuf.occupy_dev_channel.Request.strDevCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mapChannel', full_name='protobuf.occupy_dev_channel.Request.mapChannel', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_MAPCHANNELENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=229,
)


_RESPOND = _descriptor.Descriptor(
  name='Respond',
  full_name='protobuf.occupy_dev_channel.Respond',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bSuccess', full_name='protobuf.occupy_dev_channel.Respond.bSuccess', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strDevCode', full_name='protobuf.occupy_dev_channel.Respond.strDevCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strErrors', full_name='protobuf.occupy_dev_channel.Respond.strErrors', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=297,
)

_REQUEST_MAPCHANNELENTRY.containing_type = _REQUEST
_REQUEST.fields_by_name['mapChannel'].message_type = _REQUEST_MAPCHANNELENTRY
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Respond'] = _RESPOND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {

  'MapChannelEntry' : _reflection.GeneratedProtocolMessageType('MapChannelEntry', (_message.Message,), {
    'DESCRIPTOR' : _REQUEST_MAPCHANNELENTRY,
    '__module__' : 'occupy_dev_channel_pb2'
    # @@protoc_insertion_point(class_scope:protobuf.occupy_dev_channel.Request.MapChannelEntry)
    })
  ,
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'occupy_dev_channel_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.occupy_dev_channel.Request)
  })
_sym_db.RegisterMessage(Request)
_sym_db.RegisterMessage(Request.MapChannelEntry)

Respond = _reflection.GeneratedProtocolMessageType('Respond', (_message.Message,), {
  'DESCRIPTOR' : _RESPOND,
  '__module__' : 'occupy_dev_channel_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.occupy_dev_channel.Respond)
  })
_sym_db.RegisterMessage(Respond)


_REQUEST_MAPCHANNELENTRY._options = None
# @@protoc_insertion_point(module_scope)
