# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tst_devs_cmd.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SZDFH_public_pb2 as SZDFH__public__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tst_devs_cmd.proto',
  package='protobuf.TST_DEVS_CMD',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12tst_devs_cmd.proto\x12\x15protobuf.TST_DEVS_CMD\x1a\x12SZDFH-public.proto\"\x91\x01\n\x07Request\x12\x12\n\nstrDevCode\x18\x01 \x01(\t\x12\x12\n\nstrCmdCode\x18\x02 \x01(\t\x12\x12\n\nstrChannel\x18\x03 \x01(\t\x12$\n\x08mapParam\x18\x04 \x01(\x0b\x32\x12.protobuf.MapParam\x12\x12\n\nkeyTcpLink\x18\x05 \x01(\x0c\x12\x10\n\x08water_id\x18\x06 \x01(\t\"\xdd\x01\n\x07Respond\x12\x12\n\nstrDevCode\x18\x01 \x01(\t\x12\x12\n\nstrCmdCode\x18\x02 \x01(\t\x12*\n\tiDevState\x18\x03 \x01(\x0e\x32\x17.protobuf.PUB_EDevState\x12\x0f\n\x07iCmdRet\x18\x04 \x01(\x05\x12\x16\n\x0cstrErrorInfo\x18\x05 \x01(\tH\x00\x12&\n\x08mapParam\x18\x06 \x01(\x0b\x32\x12.protobuf.MapParamH\x00\x12\x12\n\nkeyTcpLink\x18\x07 \x01(\x0c\x12\x10\n\x08water_id\x18\x08 \x01(\tB\x07\n\x05paramb\x06proto3'
  ,
  dependencies=[SZDFH__public__pb2.DESCRIPTOR,])




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='protobuf.TST_DEVS_CMD.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='strDevCode', full_name='protobuf.TST_DEVS_CMD.Request.strDevCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strCmdCode', full_name='protobuf.TST_DEVS_CMD.Request.strCmdCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strChannel', full_name='protobuf.TST_DEVS_CMD.Request.strChannel', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mapParam', full_name='protobuf.TST_DEVS_CMD.Request.mapParam', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keyTcpLink', full_name='protobuf.TST_DEVS_CMD.Request.keyTcpLink', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='water_id', full_name='protobuf.TST_DEVS_CMD.Request.water_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=211,
)


_RESPOND = _descriptor.Descriptor(
  name='Respond',
  full_name='protobuf.TST_DEVS_CMD.Respond',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='strDevCode', full_name='protobuf.TST_DEVS_CMD.Respond.strDevCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strCmdCode', full_name='protobuf.TST_DEVS_CMD.Respond.strCmdCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iDevState', full_name='protobuf.TST_DEVS_CMD.Respond.iDevState', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iCmdRet', full_name='protobuf.TST_DEVS_CMD.Respond.iCmdRet', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strErrorInfo', full_name='protobuf.TST_DEVS_CMD.Respond.strErrorInfo', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mapParam', full_name='protobuf.TST_DEVS_CMD.Respond.mapParam', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keyTcpLink', full_name='protobuf.TST_DEVS_CMD.Respond.keyTcpLink', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='water_id', full_name='protobuf.TST_DEVS_CMD.Respond.water_id', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='param', full_name='protobuf.TST_DEVS_CMD.Respond.param',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=214,
  serialized_end=435,
)

_REQUEST.fields_by_name['mapParam'].message_type = SZDFH__public__pb2._MAPPARAM
_RESPOND.fields_by_name['iDevState'].enum_type = SZDFH__public__pb2._PUB_EDEVSTATE
_RESPOND.fields_by_name['mapParam'].message_type = SZDFH__public__pb2._MAPPARAM
_RESPOND.oneofs_by_name['param'].fields.append(
  _RESPOND.fields_by_name['strErrorInfo'])
_RESPOND.fields_by_name['strErrorInfo'].containing_oneof = _RESPOND.oneofs_by_name['param']
_RESPOND.oneofs_by_name['param'].fields.append(
  _RESPOND.fields_by_name['mapParam'])
_RESPOND.fields_by_name['mapParam'].containing_oneof = _RESPOND.oneofs_by_name['param']
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Respond'] = _RESPOND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'tst_devs_cmd_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.TST_DEVS_CMD.Request)
  })
_sym_db.RegisterMessage(Request)

Respond = _reflection.GeneratedProtocolMessageType('Respond', (_message.Message,), {
  'DESCRIPTOR' : _RESPOND,
  '__module__' : 'tst_devs_cmd_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.TST_DEVS_CMD.Respond)
  })
_sym_db.RegisterMessage(Respond)


# @@protoc_insertion_point(module_scope)
