# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tst_devs_pushparam.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SZDFH_public_pb2 as SZDFH__public__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tst_devs_pushparam.proto',
  package='protobuf.TST_DEVS_PUSHPARAM',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18tst_devs_pushparam.proto\x12\x1bprotobuf.TST_DEVS_PUSHPARAM\x1a\x12SZDFH-public.proto\"\xce\x01\n\x04Push\x12\x12\n\nstrDevCode\x18\x01 \x01(\t\x12\x12\n\ndbDatetime\x18\x02 \x01(\x01\x12G\n\x0bmapProperty\x18\x03 \x03(\x0b\x32\x32.protobuf.TST_DEVS_PUSHPARAM.Push.MapPropertyEntry\x12\x10\n\x08water_id\x18\x04 \x01(\t\x1a\x43\n\x10MapPropertyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.protobuf.Param:\x02\x38\x01\x62\x06proto3'
  ,
  dependencies=[SZDFH__public__pb2.DESCRIPTOR,])




_PUSH_MAPPROPERTYENTRY = _descriptor.Descriptor(
  name='MapPropertyEntry',
  full_name='protobuf.TST_DEVS_PUSHPARAM.Push.MapPropertyEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='protobuf.TST_DEVS_PUSHPARAM.Push.MapPropertyEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='protobuf.TST_DEVS_PUSHPARAM.Push.MapPropertyEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=284,
)

_PUSH = _descriptor.Descriptor(
  name='Push',
  full_name='protobuf.TST_DEVS_PUSHPARAM.Push',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='strDevCode', full_name='protobuf.TST_DEVS_PUSHPARAM.Push.strDevCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dbDatetime', full_name='protobuf.TST_DEVS_PUSHPARAM.Push.dbDatetime', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mapProperty', full_name='protobuf.TST_DEVS_PUSHPARAM.Push.mapProperty', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='water_id', full_name='protobuf.TST_DEVS_PUSHPARAM.Push.water_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PUSH_MAPPROPERTYENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=284,
)

_PUSH_MAPPROPERTYENTRY.fields_by_name['value'].message_type = SZDFH__public__pb2._PARAM
_PUSH_MAPPROPERTYENTRY.containing_type = _PUSH
_PUSH.fields_by_name['mapProperty'].message_type = _PUSH_MAPPROPERTYENTRY
DESCRIPTOR.message_types_by_name['Push'] = _PUSH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Push = _reflection.GeneratedProtocolMessageType('Push', (_message.Message,), {

  'MapPropertyEntry' : _reflection.GeneratedProtocolMessageType('MapPropertyEntry', (_message.Message,), {
    'DESCRIPTOR' : _PUSH_MAPPROPERTYENTRY,
    '__module__' : 'tst_devs_pushparam_pb2'
    # @@protoc_insertion_point(class_scope:protobuf.TST_DEVS_PUSHPARAM.Push.MapPropertyEntry)
    })
  ,
  'DESCRIPTOR' : _PUSH,
  '__module__' : 'tst_devs_pushparam_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.TST_DEVS_PUSHPARAM.Push)
  })
_sym_db.RegisterMessage(Push)
_sym_db.RegisterMessage(Push.MapPropertyEntry)


_PUSH_MAPPROPERTYENTRY._options = None
# @@protoc_insertion_point(module_scope)
