# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tst_devs_start.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SZDFH_public_pb2 as SZDFH__public__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tst_devs_start.proto',
  package='protobuf.TST_DEVS_START',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14tst_devs_start.proto\x12\x17protobuf.TST_DEVS_START\x1a\x12SZDFH-public.proto\"\x94\x01\n\x07Request\x12:\n\x05_Devs\x18\x01 \x03(\x0b\x32+.protobuf.TST_DEVS_START.Request.TST_DEVS_S\x1aM\n\nTST_DEVS_S\x12\x12\n\nstrDevCode\x18\x01 \x01(\t\x12\x14\n\x0cstrDevRunXML\x18\x02 \x01(\t\x12\x15\n\rstrDevDllName\x18\x03 \x01(\t\"o\n\x07Respond\x12\x12\n\nstrDevCode\x18\x01 \x01(\t\x12*\n\teDevState\x18\x02 \x01(\x0e\x32\x17.protobuf.PUB_EDevState\x12\x10\n\x08strError\x18\x03 \x01(\t\x12\x12\n\nkeyTcpLink\x18\x04 \x01(\x0c\x62\x06proto3'
  ,
  dependencies=[SZDFH__public__pb2.DESCRIPTOR,])




_REQUEST_TST_DEVS_S = _descriptor.Descriptor(
  name='TST_DEVS_S',
  full_name='protobuf.TST_DEVS_START.Request.TST_DEVS_S',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='strDevCode', full_name='protobuf.TST_DEVS_START.Request.TST_DEVS_S.strDevCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strDevRunXML', full_name='protobuf.TST_DEVS_START.Request.TST_DEVS_S.strDevRunXML', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strDevDllName', full_name='protobuf.TST_DEVS_START.Request.TST_DEVS_S.strDevDllName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=218,
)

_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='protobuf.TST_DEVS_START.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='_Devs', full_name='protobuf.TST_DEVS_START.Request._Devs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_TST_DEVS_S, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=218,
)


_RESPOND = _descriptor.Descriptor(
  name='Respond',
  full_name='protobuf.TST_DEVS_START.Respond',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='strDevCode', full_name='protobuf.TST_DEVS_START.Respond.strDevCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eDevState', full_name='protobuf.TST_DEVS_START.Respond.eDevState', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strError', full_name='protobuf.TST_DEVS_START.Respond.strError', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keyTcpLink', full_name='protobuf.TST_DEVS_START.Respond.keyTcpLink', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=331,
)

_REQUEST_TST_DEVS_S.containing_type = _REQUEST
_REQUEST.fields_by_name['_Devs'].message_type = _REQUEST_TST_DEVS_S
_RESPOND.fields_by_name['eDevState'].enum_type = SZDFH__public__pb2._PUB_EDEVSTATE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Respond'] = _RESPOND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {

  'TST_DEVS_S' : _reflection.GeneratedProtocolMessageType('TST_DEVS_S', (_message.Message,), {
    'DESCRIPTOR' : _REQUEST_TST_DEVS_S,
    '__module__' : 'tst_devs_start_pb2'
    # @@protoc_insertion_point(class_scope:protobuf.TST_DEVS_START.Request.TST_DEVS_S)
    })
  ,
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'tst_devs_start_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.TST_DEVS_START.Request)
  })
_sym_db.RegisterMessage(Request)
_sym_db.RegisterMessage(Request.TST_DEVS_S)

Respond = _reflection.GeneratedProtocolMessageType('Respond', (_message.Message,), {
  'DESCRIPTOR' : _RESPOND,
  '__module__' : 'tst_devs_start_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.TST_DEVS_START.Respond)
  })
_sym_db.RegisterMessage(Respond)


# @@protoc_insertion_point(module_scope)
