# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tst_devs_subscribeparam.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tst_devs_subscribeparam.proto',
  package='protobuf.TST_DEVS_SUBSCRIBEPARAM',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dtst_devs_subscribeparam.proto\x12 protobuf.TST_DEVS_SUBSCRIBEPARAM\"Y\n\x07Request\x12\x12\n\nstrDevCode\x18\x01 \x01(\t\x12\x12\n\nbSubScribe\x18\x02 \x01(\x08\x12\x14\n\x0cstrParamCode\x18\x03 \x03(\t\x12\x10\n\x08water_id\x18\x04 \x01(\t\"g\n\x07Respond\x12\x12\n\nstrDevCode\x18\x01 \x01(\t\x12\x12\n\nbSubScribe\x18\x02 \x01(\x08\x12\x10\n\x08\x62Success\x18\x03 \x01(\x08\x12\x10\n\x08strError\x18\x04 \x01(\t\x12\x10\n\x08water_id\x18\x05 \x01(\tb\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='protobuf.TST_DEVS_SUBSCRIBEPARAM.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='strDevCode', full_name='protobuf.TST_DEVS_SUBSCRIBEPARAM.Request.strDevCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bSubScribe', full_name='protobuf.TST_DEVS_SUBSCRIBEPARAM.Request.bSubScribe', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strParamCode', full_name='protobuf.TST_DEVS_SUBSCRIBEPARAM.Request.strParamCode', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='water_id', full_name='protobuf.TST_DEVS_SUBSCRIBEPARAM.Request.water_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=156,
)


_RESPOND = _descriptor.Descriptor(
  name='Respond',
  full_name='protobuf.TST_DEVS_SUBSCRIBEPARAM.Respond',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='strDevCode', full_name='protobuf.TST_DEVS_SUBSCRIBEPARAM.Respond.strDevCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bSubScribe', full_name='protobuf.TST_DEVS_SUBSCRIBEPARAM.Respond.bSubScribe', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bSuccess', full_name='protobuf.TST_DEVS_SUBSCRIBEPARAM.Respond.bSuccess', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strError', full_name='protobuf.TST_DEVS_SUBSCRIBEPARAM.Respond.strError', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='water_id', full_name='protobuf.TST_DEVS_SUBSCRIBEPARAM.Respond.water_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=261,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Respond'] = _RESPOND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'tst_devs_subscribeparam_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.TST_DEVS_SUBSCRIBEPARAM.Request)
  })
_sym_db.RegisterMessage(Request)

Respond = _reflection.GeneratedProtocolMessageType('Respond', (_message.Message,), {
  'DESCRIPTOR' : _RESPOND,
  '__module__' : 'tst_devs_subscribeparam_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.TST_DEVS_SUBSCRIBEPARAM.Respond)
  })
_sym_db.RegisterMessage(Respond)


# @@protoc_insertion_point(module_scope)
